language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn workspace client lint
  - yarn workspace server lint
  - CI=true yarn workspace client test --coverage --watch=false
  - CI=true yarn workspace server test --coverage --watch=false
  - yarn workspace client build
  - yarn workspace server build
after_success:
  - cat coverage/lcov.info | yarn coveralls
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
